# Generated by Django 4.1.3 on 2022-11-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('spending_date', models.DateTimeField(verbose_name='date of spending')),
                ('spender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_record_app.spender')),
            ],
        ),
    ]
