# Generated by Django 4.1.3 on 2022-11-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record_app', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spending_date',
            field=models.DateField(verbose_name='date of spending'),
        ),
    ]
